// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_A4LnOp25RTH9GQiH_jCiS3uGXJPe3cM',
    appId: '1:918954290804:web:f967496e4d24b43f1e6b21',
    messagingSenderId: '918954290804',
    projectId: 'itbook-bd53a',
    authDomain: 'itbook-bd53a.firebaseapp.com',
    storageBucket: 'itbook-bd53a.appspot.com',
    measurementId: 'G-JSK6HJZ7N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKUWeDkajmV7zDcNr7Ie-9_8xckXQz9ds',
    appId: '1:918954290804:android:1328dcba117698591e6b21',
    messagingSenderId: '918954290804',
    projectId: 'itbook-bd53a',
    storageBucket: 'itbook-bd53a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz0qRG1w8dXjPmPIbLJUsSs7eHnKLQKJo',
    appId: '1:918954290804:ios:b37da225e1ea36181e6b21',
    messagingSenderId: '918954290804',
    projectId: 'itbook-bd53a',
    storageBucket: 'itbook-bd53a.appspot.com',
    iosBundleId: 'com.prueba.app.inlaze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz0qRG1w8dXjPmPIbLJUsSs7eHnKLQKJo',
    appId: '1:918954290804:ios:b37da225e1ea36181e6b21',
    messagingSenderId: '918954290804',
    projectId: 'itbook-bd53a',
    storageBucket: 'itbook-bd53a.appspot.com',
    iosBundleId: 'com.prueba.app.inlaze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_A4LnOp25RTH9GQiH_jCiS3uGXJPe3cM',
    appId: '1:918954290804:web:3ad81971f7abe4a61e6b21',
    messagingSenderId: '918954290804',
    projectId: 'itbook-bd53a',
    authDomain: 'itbook-bd53a.firebaseapp.com',
    storageBucket: 'itbook-bd53a.appspot.com',
    measurementId: 'G-1NSZ6JZ7FX',
  );
}
